export const GET_PROFILE = 'GET_PROFILE';
export const GETTING_PROFILE = 'GETTING_PROFILE';
export const GETTING_PROFILE_SUCCESS = 'GETTING_PROFILE_SUCCESS';
export const GETTING_PROFILE_FAILURE = 'GETTING_PROFILE_FAILURE';
export const CREATING_PROFILE = 'CREATING_PROFILE';
export const CREATING_PROFILE_SUCCESS = 'CREATING_PROFILE_SUCCESS';
export const CREATING_PROFILE_ERROR = 'CREATING_PROFILE_ERROR';
export const UPDATE_PROFILE = 'UPDATE_PROFILE';
export const UPDATING_PROFILE = 'UPDATING_PROFILE';
export const UPDATING_PROFILE_ERROR = 'UPDATING_PROFILE_ERROR';
export const UPDATING_PROFILE_SUCCESS = 'UPDATING_PROFILE_SUCCESS';
export const PROFILE_CREATED = 'PROFILE_CREATED';
export const PROFILE_RESET = 'PROFILE_RESET';


