export const GET_USERS = 'GET_USERS';
export const GETTING_USERS = 'GETTING_USERS';
export const GETTING_USERS_FAILURE = 'GETTING_USERS_FAILURE';
export const ADD_USER = 'ADD_USER';
export const ADDING_USER = 'ADDING_USER';
export const ADDING_USER_FAILURE = 'ADDING_USER_FAILURE';
export const REMOVE_USER = 'REMOVE_USER';
export const REMOVING_USER = 'REMOVING_USER';
export const REMOVING_USER_FAILURE = 'REMOVING_USER_FAILURE';

